### ISSUE TITLE
Request: support for container tabs

### ISSUE THREAD

**Issue by mrjohnson22** [fluks/redirect-link#10]
When using redirect-link from a container tab, the link should be opened in the container belonging to the current tab. This is useful for redirecting to pages that require being signed in to an account.

**Comment by fluks** [comment]
Yes, we should stay in a container of course. Thank you, I will look into this.

**Comment by fluks** [comment]
This feature is easy to implement. I think I will add an option to not stay in a container, similar to switching to the new tab. One possibility is to add these options for every redirection individually.

**Comment by fluks** [comment]
Implemented in 3df73613a71142f92f28453e54aed743a1bb526d.

**Comment by mrjohnson22** [comment]
Thank you for implementing this so quickly! It works like a charm.
