### ISSUE TITLE
Add always redirect checkbox?

### ISSUE THREAD

**Issue by fluks** [fluks/redirect-link#12]
Maybe some URLs are such that user wants to redirect them always. If Enable URL is checked, allow user to check another box to always redirect.

This can be implemented using webRequest API, the same permission is also required.

**Comment by atomGit** [comment]
indeed, i think this extension would gain a new usefulness if an auto-redirect option was added

**Comment by fluks** [comment]
I played with [webRequest.onBeforeRequest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest) event some time ago. According to documentation it's triggered before the request is made and you don't have to care about CSP.

I didn't know which [resource types](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType) i should redirect.
You have to use match patterns with that event, it limits the enable URLs to simpler patterns. I think there is another way to always redirect requests, but I thought it is slower than webRequest.onBeforeRequest.

**Comment by atomGit** [comment]
if you need ideas, there's probably a lot of add-ons that could be studied including uBlock Origin, uMatrix, Header Editor, HTTPZ (maybe not this one), etc., all of which intercept the target before a request is sent and then redirect it

the big thing here is privacy - if someone always wants to redirect youtube.com to invidio.us, you want to avoid any connection to youtube.com

not-a-coder, (not JS anyway) so i'm not sure anything i can offer is worth offering

**Comment by Mike-Reddick** [comment]
this feature is like "Redirector" addon,

**Comment by fluks** [comment]
Commit 28678b731958443d57cb8f80ef58578a5ca64e7f implements this.
