### ISSUE TITLE
Add a toolbar button?

### ISSUE THREAD

**Issue by StanGets** [fluks/redirect-link#15]
Hi,

I think a toolbar button with exactly the same drop-down menu as the native right-click one would come in handy in two situations:

1- The page has its own right-click menu (such as i.e. Google Maps) which means Shift+right-click mandatory for accessing the regular menu;

2- The user accesses _Redirect Link_ links often, having to right-click and access the _Redirect Link_ menu item when this right-click menu includes several other extensions' items is cumbersome.

I use an extension which faced the same request: [Bookmarklets context menu](https://github.com/mems/bookmarklets-context-menu), and the [argument developed by a user](https://github.com/mems/bookmarklets-context-menu/issues/3) applies IMO to _Redirect Link_.

Whatever, thanks for this great extension, so efficient and flexible.

**Comment by fluks** [comment]
1- The page has its own right-click menu (such as i.e. Google Maps) which means Shift+right-click mandatory for accessing the regular menu

I didn't know about this trick.

    2- The user accesses Redirect Link links often, having to right-click and access the Redirect Link menu item when this right-click menu includes several other extensions' items is cumbersome.

I guess it might be a little bit easier to use the toolbar popup. You can use the toolbar only for the current page then, not for a link.

Good thing about this change is, that it's about adding code, I don't have to change existing code, not much anyway. I'll think about it.

**Comment by StanGets** [comment]
> You can use the toolbar only for the current page then, not for a link.

Indeed, and that means taking full advantage of _Redirect Link_ given one of the great things about it is that it handles pages as well as links. It works perfectly in both situations but when a redirect link concerns a page indeed having the toolbar button would be really welcomed, as I see it of course.

> Good thing about this change is, that it's about adding code, I don't have to change existing code, not much anyway. I'll think about it.

Existing code is great, don't change anything!

Thanks for taking into consideration the idea and, hum... long live _Redirect Link_!

**Comment by fluks** [comment]
I pushed a version with a toolbar button to a [new branch](https://github.com/fluks/redirect-link/tree/browser-action) if you want to test it before I'll update it in AMO. If you can't test with just plain code, I uploaded an [xpi](https://we.tl/t-eC1X3dktDW) file also. You can install it after setting about:config?filter=xpinstall.signatures.required to false and then in about:addons click the cog icon and install add-on from file.

This works in Firefox, btw, I haven't tested in Chrome.

**Comment by StanGets** [comment]
@fluks I opted for the xpi unsigned installer you've hosted on WeTransfer, I've set `xpinstall.signatures.required` to `false`, but that setting doesn't make it anymore on Firefox Quantum and trying to install your xpi from the Add-ons Manager led to

![1](https://user-images.githubusercontent.com/42912760/54936413-b70bd880-4f22-11e9-822d-afb7c8089f92.png)

Unfortunately I'm not skilled enough to test with just plain code from the new branch.

Let me know how I can possibly do to test this new version, not to mention a new version I'm eager to discover.

**Comment by StanGets** [comment]
I just remembered it was possible to install temporarily an extension from Firefox's about:debugging / _Load Temporary add-on_ (no need to set `xpinstall.signatures.required` to `false`).

The xpi installed correctly, toolbar button as well, drop-down toolbarsur button works fine, no pproblem.
Unfortunately because it's been installed temporarily it won't survive after Firefox restart ...

**Comment by fluks** [comment]
>  opted for the xpi unsigned installer you've hosted on WeTransfer, I've set `xpinstall.signatures.required` to `false`, but that setting doesn't make it anymore on Firefox Quantum

That's weird, I just tried it again on Firefox 66.0.1 and I was able to install it in a new profile.

**Comment by StanGets** [comment]
> That's weird, I just tried it again on Firefox 66.0.1 and I was able to install it in a new profile.

[Add-on signing in Firefox](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u) states,

> Firefox Extended Support Release (ESR), Firefox Developer Edition and Nightly versions of Firefox will allow you to override the setting to enforce the extension signing requirement, by changing the preference xpinstall.signatures.required to false in the Firefox Configuration Editor (about:config page). 

Maybe this explains that ...

**Comment by fluks** [comment]
Setting that preference to false works on Firefox from packages on Kubuntu. The maintainer must be compiling it in such a way that it works. I downloaded Firefox from mozilla.org and it didn't work in that version.

**Comment by StanGets** [comment]
Anyway the new version with a toolbar button as I've tested it seems to work flawlessly. Eager to have it available on AMO. Nice work @fluks. The toolbar button's drop-down menu with the available page redirects displayed as 3D buttons is nice.

**Comment by fluks** [comment]
They are regular buttons, I didn't do anything to them. Personally, I don't care about the looks hardly at all, just functionality.

I'll test it a little bit more to make sure everything works, only a minor change was needed, so nothing should break. I'll push it to AMO soon.

**Comment by StanGets** [comment]
Regular buttons, but buttons rather than a plain drop-down list of links, that's what I meant.

I care about the look when it enhances the use, makes it more intuitive, perceptible to the user. This said if functionality is indeed the major point (I've seen users on AMO lower their ratings for the sole reason of an extension's skin!) it does have its importance IMO (though secondary) because life has never been and will never be a plain matrix : aesthetics on the Web, in applications participate to a user's comfort.

**Comment by fluks** [comment]
I uploaded new version to AMO now.

Feature implemented in 0e58df0a8a7484e8783b763d793bbf0f7932c0d1.

**Comment by StanGets** [comment]
_Redirect Liink_ updated to version 2.3.0, a real pleasure, works nicely.
