### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by Mike-Reddick** [fluks/redirect-link#19]
Please add drag 'n drop to manual list sort, and export 'n import for settings and redirects, and make redirects respect mouse buttons for target, ex. middle click new tab, right click current tab.

thanks

**Comment by sergeevabc** [comment]
Err… This addon overrides tabs behaviour.
I don’t need a new tab to be opened, how to open the result in the same tab?

**Comment by fluks** [comment]
> Err… This addon overrides tabs behaviour.
> I don’t need a new tab to be opened, how to open the result in the same tab?
This is not possible currently. I need to add an option to not open a new tab or honor tabs behavior.

**Comment by fluks** [comment]
> Please add drag 'n drop to manual list sort, and export 'n import for settings and redirects, and make redirects respect mouse buttons for target, ex. middle click new tab, right click current tab.

What do you mean by drag 'n' drop to manual list sort? You can sort redirects now by pressing ctrl + alt and left mouse button.

I will add at least importing and exporting settings. 

OK, and the last one is the same @sergeevabc said.

These will have to wait for a little while, I don't have time now.

Thanks for your suggestions.

**Comment by Mike-Reddick** [comment]
All Right! About drag 'n drop with ctrl + alt and left mouse button, is exactly it I wanted, but it is not documented right? You can add an "tip" on plugin description text. About new tab behavior I think ideal is respect the mouse buttons. Importing and exporting can be very fine.

Thanks the attention and replies!

**Comment by fluks** [comment]
> All Right! About drag 'n drop with ctrl + alt and left mouse button, is exactly it I wanted, but it is not documented right?

It's here on GitHub in the readme and in the description on AMO.

Remember to the save the settings.

> You can add an "tip" on plugin description text.

Maybe I could add a help text to the options page explaining all the features. And implement drag n' drop in a way that is visible. Having a button or something you can press and drag.

> About new tab behavior I think ideal is respect the mouse buttons.

Yes. Only drawback with this is that it changes the current behavior and it will surprise users at first, even when I add it to the changelog. Left mouse button would redirect the current tab and the middle would open a new tab, right?

**Comment by fluks** [comment]
When importing settings, should we delete all the current redirects or should we add the new redirects to the current redirects? In the latter case, if one of the current redirects and one of the imported redirects have the same title, should the imported redirect overwrite the old one? Since titles can't be the same.

**Comment by Mike-Reddick** [comment]
Good idea about an button to easy toggle the drag 'n drop, and you said:

> Left mouse button would redirect the current tab and the middle would open a new tab, right?

Yes, Right! Perfect!

And about Import/Export,  I think you can even ask the user "Replace or Add Redirects?" But to be honest I think which you can implement just the Replace Mode, deleting all the current redirects, just an Simple and Basic Import/Export, if possible keeping the redirects list order. So is very fine!

Thanks so much!

**Comment by fluks** [comment]
Middle click implemented in 0421cad and export&import in 2bdb774.

**Comment by Mike-Reddick** [comment]
Thanks so much your attention!
