### ISSUE TITLE
Drag 'n Drop Bug

### ISSUE THREAD

**Issue by Mike-Reddick** [fluks/redirect-link#22]
After the implementation of the excellent feature Drag 'n Drop, have an issue, you can't select an text using drag, for instance for edit an redirector url

**Comment by fluks** [comment]
I noticed this when I implemented the DnD feature, but I thought it was so minor bug I didn't care. But I'll look can this be fixed.

**Comment by fluks** [comment]
There's a bug report about this on Bugzilla https://bugzilla.mozilla.org/show_bug.cgi?id=800050.

**Comment by fluks** [comment]
Someone presented a solution in the issue report. So I think I can use this to fix the bug.

```
--- Comment #22 from brimblecombea@gmail.com 2022-06-16 07:01:10 EEST ---
Just came across this. Applied a workaround to only set draggable to true when
needed. 
```

```html
<!doctype html>

<div id="outer" style="touch-action : none;">
    <div id="drag-handle">
        <span>drag me!</span>
    </div>

    <div>
        <input type="text" value="abc">
    </div>
</div>

<script>
    var outerDiv = document.getElementById("outer");
    var dragHandle = document.getElementById("drag-handle");

    dragHandle.onmousedown = e => outerDiv.draggable = true;
    dragHandle.onmouseup = e => outerDiv.draggable = false;
    outerDiv.ondragend = e => outerDiv.draggable = false;
</script>
```

**Comment by fluks** [comment]
https://github.com/fluks/redirect-link/commit/ebb64c80f62466637ed56c5239358ce6b8af8c1a fixes this bug.
