### ISSUE TITLE
No issue, only help for a regex!

### ISSUE THREAD

**Issue by Cade66** [fluks/redirect-link#26]
Hi,

Enjoying Redirect Link and managed to deal with several regex, but I'm facing a problem for which your help would really be appreciated.

Aim is to redirect an OpenStreetMap url to its equivalent Facilmap url.

Example:
OpenStreetMap : `https://www.openstreetmap.org/#map=6/47.000/3.000`
FacilMap : `https://facilmap.org/#6/47.000/3.000/Mpnk`

What I've set and doesn't work at all is:
URL : `https://facilmap.org/#%q[map]/Mpnk `
Enable URL : `(.*//.*)(openstreetmap.org)/(#map=)(.*)`

What am I doing wrong?! Is it the `#` which is problematic? I've brain-stormed for hours, cannot figure it out. 
Thanks for taking on your time for answering to what is not the extension's issue but my ignorance!

**Comment by fluks** [comment]
You aren't using a regex. You are you using %q, which is for the query parameters of the URL. They are key value pairs which come after ?. In a URL what comes after # is a fragment.

This redirection can be done with actually using a regex. This should work, I tested it.

`https://facilmap.org/#%r[#map=(.*)]/Mpnk`

**Comment by Cade66** [comment]
@fluks, many thanks : your redirection works perfectly.

I have indeed misused the term regex which I referred to because in my mind an _Enable Url_ which includes a `*` goes in that category!
Don't try to understand :=) Call it a neophyte's confused mind.

This said, what I had tried to do was simply adjusting another similar redirection which works:

URL: `https://piped.kavin.rocks/watch?v=%q[v]`
Enable URL: `(.*//.*)(youtube.com)/(watch\?v=)(.*)`

Anyway, many thanks for your help. Most appreciated, really.

**Comment by fluks** [comment]
> I have indeed misused the term regex which I referred to because in my mind an _Enable Url_ which includes a `*` goes in that category! Don't try to understand :=) Call it a neophyte's confused mind.

You indeed used a regex in enable URL. I was focused on the redirect URL because that's where the problem was.
