### ISSUE TITLE
How to include domain without prefix?

### ISSUE THREAD

**Issue by Cade66** [fluks/redirect-link#27]
Hi,

Sorry for the terminology.
I need to redirect a site without its "prefix" (not sure this is the correct term):
I have a redirection which requires `example.com` when the site is actually `www.example.com`:

`https://securityscorecard.com/security-rating/example.com` is accepted
`https://securityscorecard.com/security-rating/www.example.com` is reused

I've set `https://securityscorecard.com/security-rating/%h` and therefor this is refused when the **hostname** is `www.example.com`

Could you please help me on how to set this redirection? Thanks!

**Comment by fluks** [comment]
%h can't be used in this case, there's no mechanism to drop the sub-domain. You need to use a regex. This might not be the simplest version but it's the first I came up with that seems to work for your case.

`https://securityscorecard.com/security-rating/%r[(?:https?:\/\/)(?:[^\.\]+\.)?([^\.\/\]+\.[^\.\/\]+)]`

**Comment by Cade66** [comment]
@fluks many thanks. A site requiring a domain without the sub-domain doesn't occur often, first time I encounter this. Other sites accept the full domain (%h) and deliver the result without the sub-domain (they do the work themselves). I most appreciate your regex, for the present case and for other similar conditions should they occur. Thanks again. You are brains :=)

**Comment by fluks** [comment]
Np, I'm glad it worked.
