### ISSUE TITLE
Port to use manifest v3

### ISSUE THREAD

**Issue by fluks** [fluks/redirect-link#30]

**Comment by AZeed18** [comment]
This is important

**Comment by fluks** [comment]
I'm working on it.

**Comment by fluks** [comment]
Doesn't affect anything else really but automatic requests. The new API doesn't support any kind of JavaScript to be used to modify the new URL. So, I think there's nothing else left to do than change always redirects to regexes before updating them in the API. Some people suggested perhaps to redirect first to web_accessible_resource and then sending the new URL back to service worker, but I don't see how to pass data dynamically to the WAR. So, that is a no go.

I will do manifest V3 only for Chromium at least for now.

**Comment by fluks** [comment]
> Doesn't affect anything else really but automatic requests. The new API doesn't support any kind of JavaScript to be used to modify the new URL. So, I think there's nothing else left to do than change always redirects to regexes before updating them in the API. Some people suggested perhaps to redirect first to web_accessible_resource and then sending the new URL back to service worker, but I don't see how to pass data dynamically to the WAR. So, that is a no go.

I think I can't do even that, so it's only regexes and capture groups in always redirects in chromiums.

**Comment by fluks** [comment]
https://github.com/fluks/redirect-link/commit/69c50ca8f14411cd544dd533601816a30adfb6f2 Should be soon on Chrome Webstore.
