### ISSUE TITLE
special conversion

### ISSUE THREAD

**Issue by deixl** [fluks/redirect-link#31]
Help, how to convert https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA/videos to https://www.youtube.com/playlist?list=UUX6OQ3DkcsbYNE6H8uQQuVA

**Comment by fluks** [comment]
`https://www.youtube.com/playlist?list=%p[1]`

If you want an enable URL, it's `https://www.youtube.com/channel/[^/]+/videos`.

**Comment by fluks** [comment]
I missed that. Do you want a redirect only for that specific channel?

**Comment by fluks** [comment]
> Match all channel IDs to the channel playlist, the key is to convert the second letter, I'll think of another way

I don't think you can do that because you can't know what the second letter will be?

**Comment by fluks** [comment]
> The second letter is always C

But it's U in the URL you want to redirect to, right? If the second letter is the same in the URL where you want to redirect to, then it can be done. If I understood correctly second letter in from in C and U in to, you want it that way? Does it always change from C to U? Do you have another example?

**Comment by fluks** [comment]
This might work.

https://www.youtube.com/playlist?list=%r[channel\/(.).+\/]U%r[channel\/..(.+)\/]
