### ISSUE TITLE
How do I open Options page?

### ISSUE THREAD

**Issue by lilydjwg** [fluks/redirect-link#32]
I'm using Firefox 115.0.2. Clicking the extension button opens the menu items. In about:addons I don't see the Options page on the right of the Details page.

**Comment by fluks** [comment]
Should be there, it's called Preferences in English.

![Screenshot_20230730_124608](https://github.com/fluks/redirect-link/assets/6079506/e8e48a18-8a46-46a9-a528-1f0c4f5f50fc)

Maybe I could a button to the toolbar window for easier access.

**Comment by lilydjwg** [comment]
Oh yes, it's there! Thanks!

 I used to find it here in the tabs (it's called 首选项 here):

![图片](https://github.com/fluks/redirect-link/assets/440661/2988059a-1ca9-4f2a-8f39-816566897ec9)

but Redirect Link doesn't have that tab:

![图片](https://github.com/fluks/redirect-link/assets/440661/93655d0c-0920-4727-bd4e-8165fa2a1865)

It would be better to make it found in more places :-)

**Comment by fluks** [comment]
Wow, sorry, I edited your comment accidentally and not making a new comment 🤣

I'll add an options button to the toolbar window.

**Comment by fluks** [comment]
Now the new version has preferences button in the toolbar window.

**Comment by khabib227** [comment]
Very good have a preferences button, thanks
