### ISSUE TITLE
Custom favicon for redirections

### ISSUE THREAD

**Issue by khabib227** [fluks/redirect-link#34]
Please add a new field to allow the user add a favicon for each redirection, with support for a online image, a url, and as base64, maybe you can copy the code from SPC plugin that has this feature including in context menu. This can make Redirect Link much more intuitive to use with a lot of redirections.

https://addons.mozilla.org/en-US/firefox/addon/searchfrompopuporcontextmenu/

**Comment by fluks** [comment]
Okay, I guess I can do that.

**Comment by fluks** [comment]
Seems like you can't change the contextmenu items' icons at runtime. So, I can add this only for the browser action.

**Comment by fluks** [comment]
But I will add uploading the favicon by a normal file input only, at first at least. Adding it many ways feels kind a bloat.

**Comment by fluks** [comment]
6fe44f55fd544fda916c110d30c98b52f664e0d0 implements this.

**Comment by Cade66** [comment]
Now that was a great idea and perfectly carried out. Personally slightly surprised with the new popup layout and mainly with favicons' size set to 32px.
I know, I'm aware @fluks did a nice work, no one else, yet I have a slight cosmetic suggestion built around the favicons's size set to 16px together with implications on the popup's css. Applied the result is:

![0](https://github.com/fluks/redirect-link/assets/65161029/ef5e2f16-8ddc-4deb-a746-816e805391f1)

The contexrt menu displays perfectly as well:
![1](https://github.com/fluks/redirect-link/assets/65161029/1f415c1b-a4bc-45b3-a1ce-f25353dbf1c8)

For whom may be interested, the related userContent.css is:

```
/* USERCONTENT.CSS - REDIRECT LINK @AMO */

/* POPUP */
@-moz-document url("moz-extension://[UUID]/browser_action/popup.html")
{

* {scrollbar-width: none !important;}
hr {display:none !important;}
body {padding: 0px 1px !important; background: #D0D0D7 !important;}
* {color:#202020 !important; font-weight:600 !important;}

.row {margin-bottom: 0px !important;}
button {margin-bottom: 2px !important; padding:0 4px !important; height:24px !important; width:300px !important;}
button:hover {background-color:unset !important; filter: invert(1) !important;}
img {width: 16px !important; height: 16px !important; margin-top:4px !important; margin-right: 5px !important;}
#redirections {margin-top: 0px !important; margin-bottom: 4px !important;}
#options-button {margin-left: 20px !important; margin-bottom: 0px !importnt; padding-left: 5px !important;}

}
``` 

That's all ;) Thanks always and again for this most valuable extension! Just proposed my 2cents cosmetic, it's really totally secondary yet, IMHO, advantages the popup layout :)

**Comment by fluks** [comment]
I can resize the favicon to 16px too and set that in the context menu to use whichever is normally shown in the user's browser. And maybe 32px is a bit too big in the browser action. I'll see if I'll change it to 16px or at least smaller than 32px.

You can't really know for sure how your addon looks like on any given system. And it's a matter of personal taste too. I don't really care that much how it looks like, so I am open to changes in UI.

**Comment by Cade66** [comment]
@fluks , cosmetics is indeed so personal and when it comes to sizes that of the user's screen is essential of course.

> And it wasn't a perfect execution this time as I screwed up a little with the context menus

Really? Where? No issues be they graphical here with Redirect Link within the context menu ...
Main thing is that Redirect Link has substantially improved since its first releases, i.e. the 'Always enable' feature and now this 'Favicon' associated to the user's rules. In my view the extension is a must have. To be honest I posted the above comment rather as a smile, driven by enthusiasm :)

**Comment by fluks** [comment]
This issue https://github.com/fluks/redirect-link/issues/39. I don't know why it didn't affect you then, it was a clear bug in the code.

I'm glad you like this addon 😄

**Comment by fluks** [comment]
The reason could be your Firefox version. The bug was that I used 32, the number, as a key in creating context menus for the favicon and it needs to be a string. And there was another bug too. I was adding a favicon when a redirection didn't have any.

But that doesn't really matter, at least the bug is now fixed, materializes it or doesn't.
