### ISSUE TITLE
Does not work when opening Librewolf

### ISSUE THREAD

**Issue by linlinxza** [fluks/redirect-link#38]
Hi,

So, whenever I open the browser, I have to go into the addon's settings and hit 'save' to make it work. Is there a fix for this?

**Comment by fluks** [comment]
I will install Librewolf and see if I can reproduce this bug, if it's specific only for that browser.

**Comment by linlinxza** [comment]
> I will install Librewolf and see if I can reproduce this bug, if it's specific only for that browser.

Cool. But I switched to Libredirect and it works fine for clicking links and redirecting them. But I'll keep your addon for other things. Like right clicking and directing a YT link to a site for downloading YT videos. It seems to work for that. But if I start the browser and type in the address bar, it will just take me to YT and not Invidious.

Also, screw regular Firefox (and all the crap that comes with it)! Librewolf ftw! lol

**Comment by fluks** [comment]
Looks like the same happens also in normal Firefox. And it happens only with always redirections.

**Comment by linlinxza** [comment]
> Looks like the same happens also in normal Firefox. And it happens only with always redirections.

Guess I'll let you look into it.

**Comment by fluks** [comment]
Should be fixed after 85f147719bc4f804f764bf0b462e06bd4bea0c14 now.

**Comment by linlinxza** [comment]
> Should be fixed after [85f1477](https://github.com/fluks/redirect-link/commit/85f147719bc4f804f764bf0b462e06bd4bea0c14) now.

Great. Thanks.
