### ISSUE TITLE
How would redirect any Facebook URL to just the main page of Startpage?

### ISSUE THREAD

**Issue by linlinxza** [fluks/redirect-link#42]
I am trying to make all social media domain requests redirect back to startpage.com?

Despite I have it set in my PiHole server to block all the social media sites (I even used letsblock.it to add filters to block these social media domains in the search engines), I am wanting to use this addon as further insurance to block all social media domains I deem as trash.  And honestly, the less tracking the better too.

I have it set like this (ex):

URL = `https://www.startpage.com/%p` Enable URL = `https://facebook.com/*`

But it doesn't work for anything like this: `https://www.facebook.com/deviantart/`

**Comment by fluks** [comment]
Try ```https://(www\.)?facebook.com/*```.

**Comment by linlinxza** [comment]
Actually, all I did was this:

URL = `https://www.startpage.com/%f` Enable URL = `.+facebook.com`

That works. And it will affect any sub domains, or if it starts with 'www'.
