### ISSUE TITLE
Wildcard subdomain for Enable URL

### ISSUE THREAD

**Issue by dave0003** [fluks/redirect-link#43]
Is there a way to specify a wildcard for the subdomain in the Enable URL?

For example:

`https://*.stackexchange.com`

would match any stackexchange.com subdomain. Currently that doesn't work, but maybe there's another way.

I'm trying to do something like this:

URL:
`https://code.whatever.social/exchange/%h/%p`

Enable URL (this doesn't work with the *):
`https://*.stackexchange.com`

So for example this:
`https://softwareengineering.stackexchange.com/questions/210399/why-is-there-a-new-in-go`

Would be redirected to this:
`https://code.whatever.social/exchange/softwareengineering.stackexchange.com/questions/210399/why-is-there-a-new-in-go`

Also, another more general question, is there a way to get the Enable URL to match either "http" or "https" so you don't need two separate rules?

**Comment by fluks** [comment]
You can use a regular expression in the enable url too. So for example this should work:

```^https?://[^\.]+\.stackexchange\.com/```

```?``` after s in https matches http and https. Maybe my example redirections can confuse because I just used ```.``` and I didn't escape dot, so it matches any character.

**Comment by dave0003** [comment]
Thank you.
