### ISSUE TITLE
[NO ISSUE] Help only for a redirection from OpenStreetMap to OpenPoiMap

### ISSUE THREAD

**Issue by aquarime** [fluks/redirect-link#44]
Hi,

Redirect Link 5.4.0 running flawlessly (Firefox 115.14.0 ESR)
I need some help for creating a redirection from openstreetmap.org to openpoimap.org
Can't manage to find the formula, seems as it'll require some regex.

OpenStreetMap url format : `https://www.openstreetmap.org/#map=[ZOOM]/[LAT]/[LON]`
OpenPoiMap url format : `https://openpoimap.org/?map=amenity&zoom=[ZOOM]&lat=[LAT]&lon=[LON] `

I've set Enable URL = `(.*//.*)(openstreetmap.org)/(#map=)(.*)` but I'd may have to set it differently. I'm blocked on this one!

Thanks for your help, if you have the time and will of course :)

**Comment by fluks** [comment]
Yeah, you need a regex and it's a little tricky with escaping right square brackets. Well, you don't have to use them, but I used in this one.

EnableURL:

`^https://www.openstreetmap.org/#map=\d+/[\d.]+/[\d.]+`

Redirect URL:

`https://openpoimap.org/?map=amenity&zoom=%r[map=(\d+)]&lat=%r[/([\d.\]+)/]&lon=%r[/([\d.\]+)$]`

Not perfect but if the enable url is always like that it should do the trick.

**Comment by fluks** [comment]
More complex regexes can be difficult to comprehend. I started programming with 

No problem. I'm glad you find it useful.

**Comment by aquarime** [comment]
Sorry to bring this back but I've just noticed that if in `https://www.openstreetmap.org/#map=[ZOOM]/[LAT]/[LON]` [LAT] or [LON] have a negative value (southern/western hemispheres' coordinates) then EnableURL = `^https://www.openstreetmap.org/#map=\d+/[\d.]+/[\d.]+` doesn't pick it up... Back to North AND Eastern hemispheres (not negative coordinates) then all is fine.

**Comment by fluks** [comment]
EnableURL:

`^https://www.openstreetmap.org/#map=\d+/-?[\d.]+/-?[\d.]+`

Redirect URL:

`https://openpoimap.org/?map=amenity&zoom=%r[map=(\d+)]&lat=%r[/(-?[\d.\]+)/]&lon=%r[/(-?[\d.\]+)$]`

That should work on those cases also. `?` means optional.

**Comment by aquarime** [comment]
That does it! NEWS (North-East-West-South, but not up & down & over & out!)
Nice. Just love it when things turn out right :)
Thanks again, @fluks , I really appreciate it.
