### ISSUE TITLE
Would be nice if the current page is supported

### ISSUE THREAD

**Issue by lilydjwg** [fluks/redirect-link#5]
E.g. when you visit a page but it reports 404, or otherwise unavailable. You can add a menu to the tab context menu.

**Comment by fluks** [comment]
Good idea. I will try to implement this.

How about if you click the right mouse button on a page, but not a link, in that case, the menu items would redirect the current page?

**Comment by fluks** [comment]
I pushed a new branch with this feature.

https://github.com/fluks/redirect-link/tree/current-page

Would you like to test the new version or are you able to test it? Or should I add a new unlisted version to AMO or Chrome WebStore?

You can redirect the current page if you click the right mouse button on a page, not a link, any kind of media nor selected text.

**Comment by lilydjwg** [comment]
I'm able to test it. It works, but I prefer to open a new tab (so e.g. I can open several archiving sites).

**Comment by fluks** [comment]
The latest commit in that branch now opens the current page in a new tab.

I am thinking about should there be a setting to open the current page in the same tab. Maybe I will just add a new version without one and see if someone wants it.

Thanks for your suggestion and testing.
